- id: '1669000240286'
  alias: Living Room Lamps Auto
  description: Turn on at 30 minutes before sunset, turn off at 9:30pm
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
    id: Sunset
  - platform: time
    at: '21:30:00'
    id: 930pm
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 930pm
      sequence:
      - service: light.turn_off
        data:
          transition: 5
        target:
          entity_id: light.living_room_end_table_lamps
  - choose:
    - conditions:
      - condition: trigger
        id: Sunset
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
          transition: 5
        target:
          entity_id: light.living_room_end_table_lamps
  mode: single
- id: '1679539697898'
  alias: Exterior Scones
  description: Turn on at 30 minutes before sunset, turn off one hour after sunrise
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
    id: Sunset-.5
  - platform: sun
    event: sunrise
    offset: +01:00:00
    id: Sunrise+1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Sunrise+1
        alias: When triggered by sunrise plus one hour
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.exterior_sconces
  - choose:
    - conditions:
      - condition: trigger
        id: Sunset-.5
        alias: When triggered by sunset minus 30 minutes
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.exterior_sconces
  mode: single
- id: '1691682104476'
  alias: Charlie's Mario Lights
  description: ''
  trigger:
  - platform: device
    device_id: a8828617c31795cfa143af8ea4546fc0
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: CAD_Pico_On
  - platform: device
    device_id: a8828617c31795cfa143af8ea4546fc0
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: CAD_Pico_Off
  - platform: device
    device_id: a8828617c31795cfa143af8ea4546fc0
    domain: lutron_caseta
    type: press
    subtype: stop
    id: CAD_Pico_Fave
  - platform: device
    device_id: a8828617c31795cfa143af8ea4546fc0
    domain: lutron_caseta
    type: press
    subtype: raise
    id: CAD_Pico_Raise
  - platform: device
    device_id: a8828617c31795cfa143af8ea4546fc0
    domain: lutron_caseta
    type: press
    subtype: lower
    id: CAD_Pico_Lower
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - CAD_Pico_On
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
          transition: 1
        target:
          entity_id:
          - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
          - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
      - service: input_select.select_option
        data:
          option: 'ON'
        target:
          entity_id: input_select.charlie_s_lights
    - conditions:
      - condition: trigger
        id:
        - CAD_Pico_Off
      sequence:
      - service: light.turn_off
        data:
          transition: 2
        target:
          entity_id:
          - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
          - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
      - service: input_select.select_option
        data:
          option: 'OFF'
        target:
          entity_id: input_select.charlie_s_lights
    - conditions:
      - condition: trigger
        id:
        - CAD_Pico_Fave
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 25
          transition: 1
        target:
          entity_id:
          - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
          - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
      - service: input_select.select_option
        data:
          option: DIM
        target:
          entity_id: input_select.charlie_s_lights
    - conditions:
      - condition: trigger
        id:
        - CAD_Pico_Raise
      sequence:
      - service: light.turn_on
        data:
          brightness_step_pct: 5
        target:
          entity_id:
          - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
          - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
    - conditions:
      - condition: trigger
        id:
        - CAD_Pico_Lower
      sequence:
      - service: light.turn_on
        data:
          brightness_step_pct: -5
        target:
          entity_id:
          - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
          - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
  mode: single
- id: '1691682551603'
  alias: Charlie's Bedtime Lights Automation
  description: Turn off Charlie's lights after 30 minutes if the time is between two
    times which are around his bedtime.
  trigger:
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    to: DIM
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    to: 'ON'
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    from: unavailable
    to: DIM
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    from: unknown
    to: DIM
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    from: unavailable
    to: 'ON'
  - platform: state
    entity_id:
    - input_select.charlie_s_lights
    from: unknown
    to: 'ON'
  condition:
  - condition: time
    after: '19:45:00'
    before: '22:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data:
      transition: 5
    target:
      entity_id:
      - light.charlies_analog_dimmer_cad1_led_mushroom_light_output_1
      - light.charlies_analog_dimmer_cad1_led_super_star_light_output_2
  mode: single
