
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  ssl_certificate: /ssl/Home+Assistant.crt
  ssl_key: /ssl/Home+Assistant.key

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize:
    zone.home:
      radius: 40

#NOTIFICATION GROUP:
notify:
  - name: "Mobile Phones"
    platform: group
    services:
    - service: mobile_app_pixel_7_pro
      data:
        data:
          ttl: 0
          priority: high
    - service: mobile_app_pixel_8_pro
      data:
        data:
          ttl: 0
          priority: high