substitutions:
  name: everything-presence-one-85fa7c
  friendly_name: EPO_FF_Office
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret EPO_FF_Office_API


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

